### ISSUE TITLE
Got validation check error.

### ISSUE THREAD

**Issue by yanglongfei908** [zrhoffman/f5vpn-arch#2]
Dear maintainer, I got error

> ==> Validating source_x86_64 files with md5sums...
    linux_f5vpn-7182.2019.0923.1.x86_64.rpm ... FAILED
==> ERROR: One or more files did not pass the validity check!

Any solution?

**Comment by zrhoffman** [comment]
That is a shame, that mirror downgraded to an older version (7160.2018.0417.1). Delete the RPM and try again at dd1f9f3561, it should work now.

Fixed in dd1f9f3561.
