### ISSUE TITLE
Package build fails

### ISSUE THREAD

**Issue by tristanrobert** [zrhoffman/f5vpn-arch#3]
Version: 7182.2019.0923.1-5
md5sums and sha256sum fail. Unable to install it on arch.
I have fixed it with `makepkg -g` but it fails because no platforms folder found.

**Comment by zrhoffman** [comment]
Do *not* try to generate your own checksums for this package. The given checksums are correct.

I just verified it works as-is... If you delete RPM and try `makepkg` again, it does not build for you?

**Comment by tristanrobert** [comment]
Nope. If you `makepkg` checksums are differents and platforms is not found.

**Comment by zrhoffman** [comment]
Would you mind sharing the checksums that do work for you?

**Comment by tristanrobert** [comment]
Sorry. I have tried again with 7182.2019.0923.1-5 and now package is building.
